geo_info/urls.py
from django.conf.urls import url
from geo_info import views

urlpatterns = [
    url(r'^$', views.country_by_ip, name='take_info'),
    url(r'^all/$', views.GeoInfoView.as_view(), name='geo_info'),
    url(r'^delete/$', views.delete_data, name='delete_data'),
]

take_geo/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home_page.html')),
    url(r'^geo_info/', include('geo_info.urls', namespace='geo_info'))
]

geo_info/models.py
from django.db import models


class GeoInfo(models.Model):
    ip = models.CharField(max_length=50)
    country = models.CharField(max_length=100)
    user_agent = models.TextField()
    headers = models.TextField()
    date = models.DateTimeField()

geo_info/views.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.views import generic
from geoip2 import database
from geo_info.models import GeoInfo
from datetime import timedelta


def country_by_ip(request):

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    # ip = '80.254.2.190'
    path = '%s/%s' % (settings.BASE_DIR, 'GeoLite2-Country.mmdb')
    reader = database.Reader(path)
    try:
        country = reader.country(ip).country.name
        headers = {k:v for k,v in request.META.iteritems() if k.startswith('HTTP')}
        user_agent = headers.get('HTTP_USER_AGENT')
        date_request = timezone.now()

        GeoInfo.objects.create(ip=ip, country=country, user_agent=user_agent,
                               headers=headers, date=date_request)
    except:
        pass
    return HttpResponse()


class GeoInfoView(generic.ListView):
    model = GeoInfo
    template_name = 'geo_info.html'
    context_object_name = 'geo_info'

    def get_queryset(self):
        date = timezone.now()-timedelta(days=3)
        return self.model.objects.filter(date__gte=date)


def delete_data(request):
    if request.method == 'POST':
        count_days = request.POST.get('days')
        if count_days:
            days = timezone.now()-timedelta(days=int(count_days))
            GeoInfo.objects.filter(date__lte=days).delete()
    return HttpResponseRedirect(reverse_lazy('geo_info:geo_info'))

templates/geo_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GeoInfo</title>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js" ></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
</head>
<body>
    <div class="navbar navbar-default" role="presentation">
    </div>
    <div class="body container-fluid">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>IP</th>
                        <th>Country</th>
                        <th>User Agent</th>
                        <th>Headers</th>
                        <th>Date</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in geo_info %}
                        <tr>
                            <td>{{ item.ip }}</td>
                            <td>{{ item.country }}</td>
                            <td>{{ item.user_agent }}</td>
                            <td>{{ item.headers }}</td>
                            <td>{{ item.date|date:"d/m/y" }}</td>
                            <td>{{ item.date.time }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a class="btn btn-default" data-toggle="modal" href="#delData">Delete old data</a>
    </div>
    <div class="panel-footer">
        <footer>
            {% now "Y" %}
        </footer>
    </div>

    <div id="delData" class="modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>Choose period in days</h4>

                </div>
                <form action="{% url 'geo_info:delete_data' %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        <label class="inline">Days:</label>
                        <input name="days" class="inline form-control" type="number" id="days" min="0" required />
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-default" value="Delete" />
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

templates/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <a href="{% url 'geo_info:take_info' %}">Take data about client</a><br/>
    <a href="{% url 'geo_info:geo_info' %}">List of all records</a>
</body>
</html>